
"use client";
import { ChangeEvent, useRef, useState } from "react";
import lamejs from "lamejs";

type Cue={id:number;start:number;end:number;text:string};
const languages=["Tamil","Malayalam","English","Hindi","Telugu","Kannada","Bengali","Marathi","Gujarati","Punjabi","Urdu","Spanish","French","German","Italian","Portuguese","Japanese","Korean","Chinese","Arabic","Russian","Turkish","Indonesian","Vietnamese","Thai"];
const voices=["Kore","Puck","Charon","Zephyr","Aoede","Leda","Orus","Callirrhoe","Iapetus","Achird","Sulafat","Schedar","Gacrux"];
const styles=["Natural","Conversational","Professional","Storytelling","Cinematic","Energetic","Calm","Documentary"];

function seconds(v:string){const x=v.trim().replace(",",".").split(":").map(Number);return x.length===3?x[0]*3600+x[1]*60+x[2]:x[0]*60+x[1]}
function parseSub(raw:string):Cue[]{const blocks=raw.replace(/\r/g,"").trim().split(/\n\s*\n/);const out:Cue[]=[];let id=1;for(const b of blocks){const lines=b.split("\n").map(x=>x.trim()).filter(Boolean);const i=lines.findIndex(x=>x.includes("-->"));if(i<0)continue;const p=lines[i].split("-->");const text=lines.slice(i+1).join("\n").replace(/<[^>]+>/g,"").trim();if(text)out.push({id:id++,start:seconds(p[0]),end:seconds(p[1].split(/\s/)[0]),text})}return out}
function fmt(s:number){const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=Math.floor(s%60);return [h,m,x].map((n,i)=>String(n).padStart(2,"0")).join(":")}
function wavFromBuffer(b:AudioBuffer){const d=b.getChannelData(0),buf=new ArrayBuffer(44+d.length*2),v=new DataView(buf);let p=0;const w=(s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(p++,s.charCodeAt(i))};w("RIFF");v.setUint32(p,36+d.length*2,true);p+=4;w("WAVEfmt ");v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,1,true);p+=2;v.setUint32(p,b.sampleRate,true);p+=4;v.setUint32(p,b.sampleRate*2,true);p+=4;v.setUint16(p,2,true);p+=2;v.setUint16(p,16,true);p+=2;w("data");v.setUint32(p,d.length*2,true);p+=4;for(const n of d){v.setInt16(p,Math.max(-1,Math.min(1,n))*32767,true);p+=2}return new Blob([buf],{type:"audio/wav"})}
async function encodeMp3(blob:Blob){const ctx=new AudioContext(),a=await ctx.decodeAudioData(await blob.arrayBuffer()),d=a.getChannelData(0),enc=new lamejs.Mp3Encoder(1,a.sampleRate,128),out:Int8Array[]=[];for(let i=0;i<d.length;i+=1152){const s=d.subarray(i,Math.min(i+1152,d.length)),p=new Int16Array(s.length);for(let j=0;j<s.length;j++)p[j]=Math.max(-1,Math.min(1,s[j]))*32767;const x=enc.encodeBuffer(p);if(x.length)out.push(x)}const end=enc.flush();if(end.length)out.push(end);await ctx.close();return new Blob(out,{type:"audio/mpeg"})}

export default function Home(){
 const [cues,setCues]=useState<Cue[]>([]),[target,setTarget]=useState("Tamil"),[mode,setMode]=useState("Natural Translation"),[voice,setVoice]=useState("Kore"),[style,setStyle]=useState("Natural"),[pron,setPron]=useState(""),[selected,setSelected]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState("Ready"),[audioUrl,setAudioUrl]=useState(""),[recordUrl,setRecordUrl]=useState(""),[recording,setRecording]=useState(false),[advanced,setAdvanced]=useState(false);
 const audioRef=useRef<HTMLAudioElement>(null),recRef=useRef<MediaRecorder|null>(null);
 async function load(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const text=await f.text();setCues(f.name.toLowerCase().endsWith(".txt")?[{id:1,start:0,end:Math.max(5,text.length/14),text}]:parseSub(text));setSelected(0);setStatus("Subtitle loaded.")}
 async function tts(c:Cue){const r=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:c.text,voice,style,language:target,pronunciation:pron})});if(!r.ok){const j=await r.json().catch(()=>({}));throw Error(j.error||"TTS failed")}return r.blob()}
 async function reading(){if(!cues.length)return;setBusy(true);try{const b=await tts(cues[selected]),u=URL.createObjectURL(b);setAudioUrl(u);if(audioRef.current){audioRef.current.src=u;await audioRef.current.play()}setStatus("Voice ready.")}catch(e){setStatus(e instanceof Error?e.message:"Failed")}finally{setBusy(false)}}
 async function record(){if(recording){recRef.current?.stop();audioRef.current?.pause();return}if(!cues.length)return;setBusy(true);try{const b=await tts(cues[selected]),u=URL.createObjectURL(b);setAudioUrl(u);if(!audioRef.current)throw Error("Audio unavailable");audioRef.current.src=u;const captureTarget=audioRef.current as HTMLAudioElement & {captureStream?:()=>MediaStream};const stream=captureTarget.captureStream?.();if(!stream)throw Error("Browser audio capture is unavailable");const r=new MediaRecorder(stream,{mimeType:"audio/webm"}),parts:BlobPart[]=[];r.ondataavailable=e=>e.data.size&&parts.push(e.data);r.onstop=()=>{setRecordUrl(URL.createObjectURL(new Blob(parts,{type:"audio/webm"})));setRecording(false);setStatus("Recording ready.")};recRef.current=r;r.start();setRecording(true);await audioRef.current.play()}catch(e){setStatus(e instanceof Error?e.message:"Recording failed")}finally{setBusy(false)}}
 async function download(){if(!cues.length)return;setBusy(true);const ctx=new AudioContext(),total=Math.max(...cues.map(c=>c.end))+2,buf=ctx.createBuffer(1,Math.ceil(total*ctx.sampleRate),ctx.sampleRate),dst=buf.getChannelData(0);try{for(let i=0;i<cues.length;i++){setStatus("Generating "+(i+1)+"/"+cues.length+"…");const a=await ctx.decodeAudioData(await(await tts(cues[i])).arrayBuffer()),src=a.getChannelData(0),off=Math.floor(cues[i].start*ctx.sampleRate);for(let j=0;j<src.length&&off+j<dst.length;j++)dst[off+j]+=src[j]}const mp3=await encodeMp3(wavFromBuffer(buf)),u=URL.createObjectURL(mp3),a=document.createElement("a");a.href=u;a.download="nexora-ai-voice.mp3";a.click();URL.revokeObjectURL(u);setStatus("MP3 downloaded.")}catch(e){setStatus(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false);await ctx.close()}}
 async function naturalize(){const c=cues[selected];if(!c)return;setBusy(true);try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:c.text,targetLanguage:target,mode})}),j=await r.json();if(!r.ok)throw Error(j.error||"Translation failed");setCues(p=>p.map(x=>x.id===c.id?{...x,text:j.text}:x));setStatus("Subtitle translated.")}catch(e){setStatus(e instanceof Error?e.message:"Translation failed")}finally{setBusy(false)}}
 return <main className="shell">
  <header><div><span className="eyebrow">NEXORA AI</span><h1>Subtitle → Natural AI Voice</h1><p>Gemini-powered voice studio for Tamil, Malayalam, English and major world languages.</p></div><span className="badge">Gemini 3.8 TTS</span></header>
  <section className="grid">
   <div className="card"><h2>1. Input</h2><label className="drop"><input type="file" accept=".srt,.vtt,.ass,.ssa,.sbv,.txt" onChange={load}/><strong>📂 Upload subtitles</strong><span>SRT · VTT · ASS · SSA · SBV · TXT</span></label><textarea placeholder="Or paste subtitles / text here…" onChange={e=>setCues([{id:1,start:0,end:Math.max(5,e.target.value.length/14),text:e.target.value}])}/>{cues.length>0&&<small>{cues.length} cues</small>}</div>
   <div className="card"><h2>2. Voice</h2><div className="row"><label>Output<select value={target} onChange={e=>setTarget(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select></label><label>Translation<select value={mode} onChange={e=>setMode(e.target.value)}><option>Natural Translation</option><option>Spoken / Conversational</option><option>Direct Translation</option><option>Professional</option></select></label></div><div className="row"><label>Voice<select value={voice} onChange={e=>setVoice(e.target.value)}>{voices.map(x=><option key={x}>{x}</option>)}</select></label><label>Style<select value={style} onChange={e=>setStyle(e.target.value)}>{styles.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Pronunciation dictionary<input value={pron} onChange={e=>setPron(e.target.value)} placeholder="Nexora = Nex-or-ah; OpenAI = Open A I"/></label><button className="secondary" disabled={!cues.length||busy} onClick={naturalize}>✨ Naturalize selected subtitle</button></div>
  </section>
  <section className="card editor"><div className="section-head"><h2>3. Subtitle Editor</h2><span>{selected+1} / {cues.length}</span></div>{cues.length?<div className="cue-list">{cues.map((c,i)=><div className={"cue "+(i===selected?"active":"")} key={c.id} onClick={()=>setSelected(i)}><div className="cue-meta">#{c.id} · {fmt(c.start)} → {fmt(c.end)}</div><textarea value={c.text} onChange={e=>setCues(p=>p.map(x=>x.id===c.id?{...x,text:e.target.value}:x))}/></div>)}</div>:<div className="empty">Upload or paste subtitles to begin.</div>}</section>
  <section className="card output"><h2>4. Output</h2><div className="outputs"><button className="primary" disabled={!cues.length||busy} onClick={reading}>🔊 READING</button><button className="danger" disabled={!cues.length||busy} onClick={record}>{recording?"⏹ STOP RECORDING":"🔴 READ + RECORD"}</button><button className="primary" disabled={!cues.length||busy} onClick={download}>⬇️ DOWNLOAD MP3</button></div><audio ref={audioRef} controls className="player" src={audioUrl}/>{recordUrl&&<div className="recorded"><strong>Recorded output</strong><audio controls src={recordUrl}/><a href={recordUrl} download="nexora-read-recording.webm">Download recording</a></div>}<p className="status">{busy?"⏳":status}</p></section>
  <section className="card advanced"><button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}>⚙️ Advanced {advanced?"▲":"▼"}</button>{advanced&&<div className="advanced-body"><div><strong>Smart Timing</strong><p>Generated audio is placed at each subtitle start time so the original timeline is respected.</p></div><div><strong>Gemini model</strong><p>Gemini 3.8 Flash TTS is used for natural, expressive speech and regional dialect coverage.</p></div><div><strong>Security</strong><p>GEMINI_API_KEY stays server-side and is never exposed to the browser.</p></div></div>}</section>
  <footer>{busy?"Working…":"Ready"} · Built for Nexora AI</footer>
 </main>
}
